accounts/urls.py
from django.urls import path, include
from django.urls import reverse_lazy
from accounts import views as accounts_views

from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [

    # change password urls
    path(
        'password_change/',
        auth_views.PasswordChangeView.as_view(
            success_url=reverse_lazy('accounts:password_change_done')
        ),
        name='password_change'
    ),
    path('', include('django.contrib.auth.urls')),
    path('profile/', accounts_views.profile, name='user-profile'),
    path('profile/update/', accounts_views.ProfileUpdate.as_view(), name='user-profile-update'),
    path('profile/image_change/', accounts_views.ChangeImageProfileView.as_view(), name='user-image-change'),
    path('detail/<int:pk>/', accounts_views.account, name='user-account'),
]

blog/urls.py
from django.urls import path
from blog import views as blog_views
from django.conf.urls import include, url

app_name = 'blog'

urlpatterns = [
    path('', blog_views.BlogView.as_view(), name='blog-index'),
    path('post/<slug:slug>/', blog_views.view_post, name='blog-view-post'),
    path('new/', blog_views.PostCreateView.as_view(), name='blog-post-new'),
    path('edit/<slug:slug>/', blog_views.PostUpdateView.as_view(), name='blog-post-edit'),
    path('delete/<slug:slug>/', blog_views.PostDeleteView.as_view(), name='blog-post-delete'),
    path('category/<slug:slug>/', blog_views.view_category, name='blog-view-category'),
    path('group/<slug:slug>/', blog_views.view_group, name='blog-view-group'),
    # rich editor urls
    url(r'^tinymce/', include('tinymce.urls')),
]

core/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('members/', include('members.urls')),
    path('cash/', include('cash.urls')),
    path('', include('blog.urls')),
    url(r'^tz_detect/', include('tz_detect.urls')),
]

accounts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.db.models.signals import post_save
from django.dispatch import receiver


class TimestampleModel(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    deleted = models.BooleanField(default=False)

    class Meta:
        abstract = True


class Lote(TimestampleModel):
    title = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('accounts:account-view-lote', args=[self.slug])

    def save(self, *args, **kwargs):
        self.slug = slugify('{title}-{id}'.format(title=self.title, id=self.pk))
        super(Lote, self).save(*args, **kwargs)

    class Meta:
        ordering = ['title']


class Profile(TimestampleModel):
    ADMIN = 1
    MANAGER = 1
    MEMBER = 2
    ROLE_CHOICES = (
        (ADMIN, 'Admin'),
        (MANAGER, 'Manager'),
        (MEMBER, 'Member'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICES, null=True, blank=True)

    first_name = models.CharField(max_length=255, blank=True)
    last_name = models.CharField(max_length=255, blank=True)
    birthdate = models.DateField(null=True, blank=True)
    lote = models.ManyToManyField(Lote, blank=True)
    telephone = models.CharField(max_length=30, blank=True)
    dni = models.CharField(max_length=30, blank=True)
    email = models.CharField(max_length=150, blank=True)
    image_url = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('accounts:user-profile')


@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

accounts/views.py
from django.http import Http404
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.shortcuts import render

from django.views import View

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic.edit import UpdateView

from django.contrib.auth.models import User
from .models import Profile

from common.upload import upload_file


@login_required
def profile(request):
    try:
        user = User.objects.get(pk=request.user.pk)
    except User.DoesNotExist:
        raise Http404("User does not exist")
    return render(request, 'accounts/profile.html', {'user': user})


@login_required
def account(request, pk):
    try:
        user = User.objects.get(pk=pk)
    except User.DoesNotExist:
        raise Http404("User does not exist")
    return render(request, 'accounts/profile.html', {'user': user})


@method_decorator(login_required, name='dispatch')
class ChangeImageProfileView(View):
    initial = {'key': 'value'}
    template_name = 'accounts/change_image_form.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'initial': self.initial})

    def post(self, request, *args, **kwargs):
        profile = Profile.objects.get_or_create(user=self.request.user)
        profile = profile[0]
        links = upload_file(self.request, 'attached_file', ['image/png', 'image/jpeg'])
        profile.image_url = links['dropbox']
        profile.save()
        return HttpResponseRedirect(reverse_lazy('accounts:user-profile'))


class ProfileUpdate(UpdateView):
    model = Profile
    fields = ['first_name', 'last_name', 'birthdate', 'lote', 'telephone', 'dni', 'email']

    def get_object(self):
        queryset = super(ProfileUpdate, self).get_queryset()
        return queryset.filter(user=self.request.user).first()

templates/accounts/change_image_form.html
{% extends 'base.html' %}

{% block title %}Account{% endblock %}
{% block section %}Profile{% endblock %}

{% block content %}

<div class="col-md-4">
  <div class="post post-sm">
  <div class="post-body">
    <h1 class="">Imagen de Perfil</h1>
  </div>
  </div>
</div>


  <form role="form" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <input type="file" name="attached_file" class="p-4">
      <button class="btn btn-outline-primary text-uppercase" type="submit">Asignar Foto</button>
  </form>
  

{% endblock %}

templates/accounts/profile.html
{% extends 'base.html' %}

{% block title %}Profile{% endblock %}
{% block section %}Profile{% endblock %}

{% block content %}


  <h2>Profile</h2>

<div class="container bootstrap snippet">

    <div class="row">
        <div class="col-sm-3"><!--left col-->
              

      <div class="text-center">

        {% if user.profile.image_url %}
            <img class="img-thumbnail" width="300" src="{{ user.profile.image_url }}" alt="Imagen de Perfil">
        {% else %}
            <img src="http://ssl.gstatic.com/accounts/ui/avatar_2x.png" class="avatar img-circle img-thumbnail" alt="avatar">
        {% endif %}

        <h6><a class="btn btn-info" href="{% url 'accounts:user-image-change' %}">Cambiar foto</a> </h6>

      </div></hr><br>

          
        </div><!--/col-3-->
        <div class="col-sm-9">
 

              <h6><a class="btn btn-info" href="{% url 'accounts:user-profile-update' %}">Actualizar Perfil</a> </h6>
          <div class="tab-content">
            <div class="tab-pane active" id="home">
                <hr>
                      <div class="form-group">
                          <div class="col-xs-6">
                              <label for="first_name"><h4>First name</h4></label>
                              {{ user.profile.first_name }}
                          </div>
                      </div>
                      <div class="form-group">
                          
                          <div class="col-xs-6">
                            <label for="last_name"><h4>Last name</h4></label>
                              {{ user.profile.last_name }}
                          </div>
                      </div>
          
                      <div class="form-group">
                          
                          <div class="col-xs-6">
                              <label for="phone"><h4>Phone</h4></label>
                              {{ user.profile.telephone }}
                          </div>
                      </div>
          
                      <div class="form-group">
                          <div class="col-xs-6">
                             <label for="mobile"><h4>DNI</h4></label>
                                {{ user.profile.dni }}
                          </div>
                      </div>
                      <div class="form-group">
                          
                          <div class="col-xs-6">
                              <label for="email"><h4>Email</h4></label>
                              {% if user.profile.email %}
                                {{ user.profile.email }}
                              {% else %}
                                {{ user.email }}
                              {% endif %}
                          </div>
                      </div>
                      <div class="form-group">
                          
                          <div class="col-xs-6">
                              <label for="email"><h4>Nacimiento</h4></label>
                              {{ user.profile.birthdate }}
                          </div>
                      </div>
                        <div class="form-group">  
                          <div class="col-xs-6">
                              <label for="email"><h4>Lotes</h4></label>
                              {% if user.profile.lote.all %}
                                {% for lote in user.profile.lote.all %}
                                    <li>{{ lote }}</li>
                                {% endfor %}
                              {% endif %}
                          </div>
                      </div>
              <hr>
             </div><!--/tab-pane-->
          </div><!--/tab-content-->

        </div><!--/col-9-->
    </div><!--/row-->

{% endblock %}

templates/accounts/profile_form.html
{% extends 'base.html' %}

{% block title %}Account{% endblock %}
{% block section %}Profile{% endblock %}

{% load widget_tweaks %}

{% block content %}

<div class="col-md-4">
  <div class="post post-sm">
  <div class="post-body">
    <h1 class="">Actualizar Perfil</h1>
  </div>
  </div>
</div>


  <form role="form" method="post" class="p-4" enctype="multipart/form-data">
      {% csrf_token %}
      
      <div class="blog-post">
        {{ form.first_name.label_tag }}
        <span class="text-danger">{{ form.first_name.errors }} </span>
        <h2 class="blog-post-title">    
        {{ form.first_name|add_class:'form-control' }}
        </h2>
      </div>

      <div class="blog-post">
        {{ form.last_name.label_tag }}
        <span class="text-danger">{{ form.last_name.errors }} </span>
        <h2 class="blog-post-title">    
        {{ form.last_name|add_class:'form-control' }}
        </h2>
      </div>


      <div class="blog-post">
        {{ form.birthdate.label_tag }}
        <span class="text-danger">{{ form.birthdate.errors }} </span>
        <h2 class="blog-post-title">    
        {{ form.birthdate|add_class:'form-control' }}
        </h2>
      </div>

       <div class="blog-post">
        {{ form.lote.label_tag }}
        <span class="text-danger">{{ form.lote.errors }} </span>
        <h2 class="blog-post-title">    
        {{ form.lote|add_class:'form-control' }}
        </h2>
      </div>

            <div class="blog-post">
        {{ form.telephone.label_tag }}
        <span class="text-danger">{{ form.telephone.errors }} </span>
        <h2 class="blog-post-title">    
        {{ form.telephone|add_class:'form-control' }}
        </h2>
      </div>

        <div class="blog-post">
        {{ form.dni.label_tag }}
        <span class="text-danger">{{ form.dni.errors }} </span>
        <h2 class="blog-post-title">    
        {{ form.dni|add_class:'form-control' }}
        </h2>
      </div>

        <div class="blog-post">
        {{ form.email.label_tag }}
        <span class="text-danger">{{ form.email.errors }} </span>
        <h2 class="blog-post-title">    
        {{ form.email|add_class:'form-control' }}
        </h2>
      </div>

  <button class="btn btn-outline-primary text-uppercase" type="submit">Actualizar</button>

  </form>
  

{% endblock %}