blog/urls.py
from django.urls import path
from blog import views as blog_views
from django.conf.urls import include, url

app_name = 'blog'

urlpatterns = [
    path('', blog_views.BlogView.as_view(), name='blog-index'),
    path('post/<slug:slug>/', blog_views.view_post, name='blog-view-post'),
    path('new/', blog_views.PostCreateView.as_view(), name='blog-post-new'),
    path('edit/<slug:slug>/', blog_views.PostUpdateView.as_view(), name='blog-post-edit'),
    path('delete/<slug:slug>/', blog_views.PostDeleteView.as_view(), name='blog-post-delete'),
    path('category/<slug:slug>/', blog_views.view_category, name='blog-view-category'),
    path('group/<slug:slug>/', blog_views.view_group, name='blog-view-group'),
    # rich editor urls
    url(r'^tinymce/', include('tinymce.urls')),
]

core/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('members/', include('members.urls')),
    path('cash/', include('cash.urls')),
    path('', include('blog.urls')),
    url(r'^tz_detect/', include('tz_detect.urls')),
]

blog/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from django.contrib.auth.models import User

from tinymce.models import HTMLField


class TimestampleModel(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    deleted = models.BooleanField(default=False)

    class Meta:
        abstract = True


class Category(TimestampleModel):
    title = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:blog-view-category', args=[self.slug])

    def save(self, *args, **kwargs):
        self.slug = slugify('{title}-{id}'.format(title=self.title, id=self.pk))
        super(Category, self).save(*args, **kwargs)

    class Meta:
        ordering = ['title']


class Group(TimestampleModel):
    title = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:blog-view-group', args=[self.slug])

    def save(self, *args, **kwargs):
        self.slug = slugify('{title}-{id}'.format(title=self.title, id=self.pk))
        super(Group, self).save(*args, **kwargs)

    class Meta:
        ordering = ['title']


class Blog(TimestampleModel):
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    summary = models.CharField(max_length=100)
    rich_body = HTMLField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image_url = models.CharField(max_length=250, blank=True, null=True)
    posted = models.DateField(db_index=True, auto_now_add=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    groups = models.ManyToManyField(Group)
    is_published = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:blog-view-post', args=[self.slug])

    def save(self, *args, **kwargs):
        self.slug = slugify('{title}-{id}'.format(title=self.title, id=self.pk))
        super(Blog, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-posted']

blog/views.py
from django.urls import reverse_lazy

from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, DeleteView
from django.http import Http404
from django.shortcuts import render
from blog.models import Blog, Category, Group

from django.db.models import Q, Count

from django.views.generic.edit import CreateView


from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required

from django.utils.decorators import method_decorator


@method_decorator(login_required, name='dispatch')
class BlogView(ListView):

    template_name = 'blog/index.html'
    model = Blog
    paginate_by = 6  # if pagination is desired
    context_object_name = 'posts'
    ordering = ['-posted']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all().annotate(
            posts_count=Count('blog', filter=Q(blog__is_published=1)),
        )
        context['groups'] = Group.objects.all().annotate(
            posts_count=Count('blog', filter=Q(blog__is_published=1)),
        )
        context['posts_draft_count'] = len(Blog.objects.filter(is_published=0))
        context['image_default'] = (
            'https://www.gumtree.com/static/1/resources/assets/rwd/images/orphans/a37b37d99e7cef805f354d47.noimage_thumbnail.png'
        )
        return context

    def get_queryset(self):
        query = self.request.GET.get('draft')
        result = Blog.objects.filter(is_published=1)
        if query == '1' and self.request.user.is_staff:
            result = Blog.objects.filter(is_published=0)
        return result


@login_required
def view_post(request, slug):
    try:
        p = Blog.objects.get(slug=slug)
    except Blog.DoesNotExist:
        raise Http404("Post does not exist")
    return render(request, 'blog/view_post.html', {'post': p})


@login_required
def view_category(request, slug):
    try:
        category = Category.objects.get(slug=slug)
    except Category.DoesNotExist:
        raise Http404("Category does not exist")
    return render(
        request,
        'blog/view_category.html',
        {
            'category': category,
            'posts': Blog.objects.filter(category=category, is_published=True)[:5],
        }
    )


@login_required
def view_group(request, slug):
    try:
        group = Group.objects.get(slug=slug)
    except Group.DoesNotExist:
        raise Http404("Group does not exist")
    return render(
        request,
        'blog/view_group.html',
        {
            'group': group,
            'posts': Blog.objects.filter(groups=group, is_published=True)[:5],
        }
    )


@method_decorator(staff_member_required, name='dispatch')
@method_decorator(login_required, name='dispatch')
class PostCreateView(CreateView):
    model = Blog
    fields = ['title', 'rich_body', 'category', 'groups', 'is_published']

    def form_valid(self, form):
        post = form.save(commit=False)
        post.author = self.request.user
        post.save()
        response = super(PostCreateView, self).form_valid(form)
        return response


@method_decorator(staff_member_required, name='dispatch')
@method_decorator(login_required, name='dispatch')
class PostUpdateView(UpdateView):
    model = Blog
    fields = ['title', 'rich_body', 'category', 'groups', 'is_published']

    def form_valid(self, form):
        post = form.save(commit=False)
        post.author = self.request.user
        post.save()
        response = super(PostUpdateView, self).form_valid(form)
        return response


@method_decorator(staff_member_required, name='dispatch')
@method_decorator(login_required, name='dispatch')
class PostDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog-index')

templates/blog/blog_confirm_delete.html
{% extends 'base.html' %}
{% load i18n %} 
{% block title %}Blog{% endblock %}
{% block section %}Post{% endblock %}

{% block content %}

{% trans "Estás seguro de que quieres eliminar a " as question %}
{% trans "Confirmar" as msg_btn %}


<form method="post">{% csrf_token %}
    <p>{{ question }} "{{ object }}"?</p>
    <input class="btn btn-danger" type="submit" value="{{ msg_btn }}">
</form>
	
{% endblock %}

templates/blog/blog_form.html
{% extends 'base.html' %}

{% load i18n %} 
{% load widget_tweaks %}

{% block title %}New post{% endblock %}
{% block section %}New post{% endblock %}

{% block content %}

{% trans "Guardar" as save %}

<form method="post" novalidate>
  {% csrf_token %}

  {% if form.non_field_errors %}
    <div class="text-center alert alert-warning alert-dismissible fade show" role="alert">
      <ul>
        {% for error in form.non_field_errors %}
          <li>{{ error }}</li>
        {% endfor %}
      </ul>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  {% endif %}

  {% for hidden_field in form.hidden_fields %}
    {% if hidden_field.errors %}
      <ul>
        {% for error in hidden_field.errors %}
          <li>(Hidden field {{ hidden_field.name }}) {{ error }}</li>
        {% endfor %}
      </ul>
    {% endif %}
    {{ hidden_field }}
  {% endfor %}

    <div class="col-md-12 blog-main">

      <div class="blog-post">
        {{ form.title.label_tag }}
        <span class="text-danger">{{ form.title.errors }} </span>
        <h2 class="blog-post-title">    
        {{ form.title|add_class:'form-control' }}
        </h2>

        <span class="text-danger">{{ form.rich_body.errors }}</span>
        {{ form.rich_body }}

        {{ form.groups.label_tag }}
        <span class="text-danger">{{ form.groups.errors }}</span>
        {{ form.groups|add_class:'form-control' }}

        {{ form.category.label_tag }}
        <span class="text-danger">{{ form.category.errors }}</span>
        {{ form.category|add_class:'form-control' }}

        <div class="form-check">
          <span class="text-danger">{{ form.is_published.errors }}</span>
          {{ form.is_published|add_class:'form-check-input' }}
          {{ form.is_published.label_tag }}
        </div>

    </div>
    <p>
      <br>
    <button class="btn btn-outline-primary text-uppercase" type="submit">{{ save }}</button>
    </p>
    </div>

  
</form>


{% endblock %}

templates/blog/index.html
{% extends 'base.html' %}
{% load i18n %} 
{% block title %}Blog{% endblock %}
{% block section %}Blog{% endblock %}

{% block content %}

{% trans "Novedades" as post_title %}
{% trans "No hay posts." as no_posts_message %}

{% trans "Categorias" as category_title %}
{% trans "No hay categorias." as no_categories_message %}

{% trans "Borradores" as draft_title %}
{% trans "No hay borradores." as no_draft_message %}

{% trans "Grupos" as group_title %}
{% trans "No hay grupos." as no_groups_message %}


<div class="jumbotron p-4 p-md-5 rounded">
    <h1 class="font-italic text-center">{{ post_title }}</h1>
</div>


<main role="main">
  <div class="row">

  
    <div class="col-md-8 blog-main p-4">
        {% if posts %}  
          {% for post in posts %}    
          <!-- POST -->
          <div class="col-md-12">
            <div class="post">
              {% if post.image_url %}
              <a class="post-img" href="{{ post.get_absolute_url }}"><img src="{{ post.image_url }}" alt="{{ post.title }}"></a>
              {% endif %}
              <div class="post-body">
                <div class="post-category">
                  {% for group in post.groups.all %} 
                    <a href="{{ group.get_absolute_url }}">{{ group.title }}</a>
                  {% endfor %}
                </div>
                <h3 class="post-title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                  <ul class="post-meta">
                  <li><a href="#">{{ post.author }}</a></li>
                  <li>{{ post.posted }}</li>
                  <li><a href="{{ post.category.get_absolute_url }}">{{ post.category }}</a></li>
                </ul>
              </div>
            </div>
          </div>
          {% endfor %}
          <!-- END POST -->
          {% else %}
          <p>{{ no_posts_message }}</p>
          {% endif %}

        <!-- Pagination -->
        <div class="d-flex justify-content-center mb-3">
            {% if is_paginated %}
            <nav>
              <ul class="pagination">
                {% if page_obj.has_previous %}
                  <li class="page-item"><a class="page-link"  href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                {% else %}
                  <li class="page-item disabled"><span class="page-link" >&laquo;</span></li>
                {% endif %}
                {% for i in paginator.page_range %}
                  {% if page_obj.number == i %}
                    <li class="page-item active"><span class="page-link" >{{ i }} <span class="sr-only">(current)</span></span></li>
                  {% else %}
                    <li class="page-item"><a class="page-link"  href="?page={{ i }}">{{ i }}</a></li>
                  {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                  <li class="page-item"><a class="page-link"  href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                {% else %}
                  <li class="page-item disabled"><span class="page-link" >&raquo;</span></li>
                {% endif %}
              </ul>
            </nav>
          {% endif %}
        </div>
         <!-- Pagination -->

    </div><!-- /.blog-main -->

    <aside class="col-md-4 blog-sidebar">

<!--       <div class="p-4 mb-3 bg-light rounded">
        <h4 class="font-italic">About</h4>
        <p class="mb-0">Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
      </div> -->
          
      {% if request.user.is_staff %}
        <div class="p-4">
        <h4 class="font-italic">{{ draft_title }}</h4>
        {% if posts_draft_count %}
        <ol class="list-unstyled mb-0">
            <li><a href="?draft=1">{{ draft_title }} (<span>{{ posts_draft_count }}</span>)</a></li>
        </ol>
        {% else %}
          <p>{{ no_draft_message }}</p>
        {% endif %}
      </div>
      {% endif %}

      <div class="p-4">
        <h4 class="font-italic">{{ category_title }}</h4>
        {% if categories %}
        <ol class="list-unstyled mb-0">
          {% for category in categories %}
            <li><a href="{{ category.get_absolute_url }}">{{ category.title }} (<span>{{ category.posts_count }}</span>)</a></li>
          {% endfor %}
        </ol>
        {% else %}
          <p>{{ no_categories_message }}</p>
        {% endif %}
      </div>

      <div class="p-4">
        <h4 class="font-italic">{{ group_title }}</h4>
        {% if groups %}
        <ol class="list-unstyled category-widget">
          {% for group in groups %}
              <li><a href="{{ group.get_absolute_url }}">{{ group.title }} (<span>{{ group.posts_count }}</span>)</a></li>
          {% endfor %}
        </ol>
      {% else %}
        <p>{{ no_groups_message }}</p>
      {% endif %}
      </div>
    </aside><!-- /.blog-sidebar -->

  </div><!-- /.row -->

</main>


{% endblock %}

templates/blog/view_category.html
{% extends 'base.html' %}
{% load i18n %} 
{% block title %}Blog{% endblock %}
{% block section %}Category{% endblock %}

{% block content %}
    

{% trans "Novedades en: " as post_title %}
{% trans "No hay posts." as no_posts_message %}

{% trans "Categoria" as category_title %}


<div id="nav-top">
  <div class="container">
    <div class="row">
      <div class="col-md-12 justify-content-center mb-3">


        <div class="row">

          <!-- TITLE RECENT POSTS -->
          <div class="col-md-12">
            <div class="section-title">
              <h2 class="title">{{ post_title }}{{ category }}</h2>
            </div>
          </div>
          <!-- END TITLE RECENT POSTS -->

          {% if posts %}  
          {% for post in posts %}    
          <!-- POST -->
          <div class="col-md-6 ">
            <div class="post">
              {% if post.image_url %}
              <a class="post-img" href="{{ post.get_absolute_url }}"><img src="{{ post.image_url }}" alt="{{ post.title }}"></a>
              {% else %}
              <a class="post-img" href="{{ post.get_absolute_url }}"><img src="{{ image_default }}" alt="{{ post.title }}"></a>
              {% endif %}
              <div class="post-body">
                <div class="post-category">
                	{% for group in post.groups.all %} 
                    <a href="{{ group.get_absolute_url }}">{{ group.title }}</a>
                  {% endfor %}
                  
                </div>
                <h3 class="post-title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                  <ul class="post-meta">
                  <li><a href="#">{{ post.author }}</a></li>
                  <li>{{ post.posted }}</li>
                  <li><a href="{{ post.category.get_absolute_url }}">{{ post.category }}</a></li>
                </ul>
              </div>
            </div>
          </div>
          {% endfor %}
          <!-- END POST -->
          {% else %}
          <p>{{ no_posts_message }}</p>
          {% endif %}

          <div class="clearfix visible-md visible-lg"></div>

        </div>
        

              <!-- Pagination -->
        <div class="d-flex justify-content-center mb-3">
            {% if is_paginated %}
            <nav>
              <ul class="pagination">
                {% if page_obj.has_previous %}
                  <li class="page-item"><a class="page-link"  href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                {% else %}
                  <li class="page-item disabled"><span class="page-link" >&laquo;</span></li>
                {% endif %}
                {% for i in paginator.page_range %}
                  {% if page_obj.number == i %}
                    <li class="page-item active"><span class="page-link" >{{ i }} <span class="sr-only">(current)</span></span></li>
                  {% else %}
                    <li class="page-item"><a class="page-link"  href="?page={{ i }}">{{ i }}</a></li>
                  {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                  <li class="page-item"><a class="page-link"  href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                {% else %}
                  <li class="page-item disabled"><span class="page-link" >&raquo;</span></li>
                {% endif %}
              </ul>
            </nav>
          {% endif %}
        </div>
         <!-- Pagination -->

      </div>
    </div>
  </div>
</div>



{% endblock %}

templates/blog/view_group.html
{% extends 'base.html' %}
{% load i18n %} 
{% block title %}Blog{% endblock %}
{% block section %}Category{% endblock %}

{% block content %}
    

{% trans "Novedades en: " as post_title %}
{% trans "No hay posts." as no_posts_message %}

{% trans "Grupo" as category_title %}


<div id="nav-top">
  <div class="container">
    <div class="row">
      <div class="col-md-12 justify-content-center mb-3">


        <div class="row">

          <!-- TITLE RECENT POSTS -->
          <div class="col-md-12">
            <div class="section-title">
              <h2 class="title">{{ post_title }}{{ group }}</h2>
            </div>
          </div>
          <!-- END TITLE RECENT POSTS -->

          {% if posts %}  
          {% for post in posts %}    
          <!-- POST -->
          <div class="col-md-6 ">
            <div class="post">
              {% if post.image_url %}
              <a class="post-img" href="{{ post.get_absolute_url }}"><img src="{{ post.image_url }}" alt="{{ post.title }}"></a>
              {% else %}
              <a class="post-img" href="{{ post.get_absolute_url }}"><img src="{{ image_default }}" alt="{{ post.title }}"></a>
              {% endif %}
              <div class="post-body">
                <div class="post-category">
                  {% for group in post.groups.all %} 
                    <a href="{{ group.get_absolute_url }}">{{ group.title }}</a>
                  {% endfor %}
                </div>
                <h3 class="post-title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                  <ul class="post-meta">
                  <li><a href="#">{{ post.author }}</a></li>
                  <li>{{ post.posted }}</li>
                  <li><a href="{{ post.category.get_absolute_url }}">{{ post.category }}</a></li>
                </ul>
              </div>
            </div>
          </div>
          {% endfor %}
          <!-- END POST -->
          {% else %}
          <p>{{ no_posts_message }}</p>
          {% endif %}

          <div class="clearfix visible-md visible-lg"></div>

        </div>
        

              <!-- Pagination -->
        <div class="d-flex justify-content-center mb-3">
            {% if is_paginated %}
            <nav>
              <ul class="pagination">
                {% if page_obj.has_previous %}
                  <li class="page-item"><a class="page-link"  href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                {% else %}
                  <li class="page-item disabled"><span class="page-link" >&laquo;</span></li>
                {% endif %}
                {% for i in paginator.page_range %}
                  {% if page_obj.number == i %}
                    <li class="page-item active"><span class="page-link" >{{ i }} <span class="sr-only">(current)</span></span></li>
                  {% else %}
                    <li class="page-item"><a class="page-link"  href="?page={{ i }}">{{ i }}</a></li>
                  {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                  <li class="page-item"><a class="page-link"  href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                {% else %}
                  <li class="page-item disabled"><span class="page-link" >&raquo;</span></li>
                {% endif %}
              </ul>
            </nav>
          {% endif %}
        </div>
         <!-- Pagination -->

      </div>
    </div>
  </div>
</div>



{% endblock %}

templates/blog/view_post.html
{% extends 'base.html' %}

{% block title %}Blog{% endblock %}
{% block section %}Post{% endblock %}

{% block content %}

<div class="col-md-4">
	<div class="post post-sm">
	<a class="post-img" href="{{ post.get_absolute_url }}"><img src="{ post.image_url }}" alt=""></a>
	<div class="post-body">
		<div class="post-category">
			<a href="{{ post.category.get_absolute_url }}">{{ post.category }}</a>
		</div>
		<h1 class=""><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h1>
		<ul class="post-meta">
			<li><a href="author.html">{{ post.author }}</a></li>
			<li>{{ post.posted }}</li>
			{% if request.user.is_staff %}
			<li><a class="btn btn-sm btn-primary" style="color: white;" href="{% url 'blog:blog-post-edit' post.slug %}">Edit</a></li>
			<li><a class="btn btn-sm btn-danger" style="color: white;" href="{% url 'blog:blog-post-delete' post.slug %}">Delete</a></li>
			{% endif %}
		</ul>
	</div>
	</div>
</div>

   <img class="card-img-top"  style="max-width:50%;height:auto;" src="{{ post.image_url }}" alt={{ post.title }}>
   <p class="display-2">{{ post.body }}</p>
   <p class="display-2">{{ post.rich_body | safe }}</p>  
	
	
	




{% endblock %}