accounts/urls.py
from django.urls import path, include
from django.urls import reverse_lazy
from accounts import views as accounts_views

from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [

    # change password urls
    path(
        'password_change/',
        auth_views.PasswordChangeView.as_view(
            success_url=reverse_lazy('accounts:password_change_done')
        ),
        name='password_change'
    ),
    path('', include('django.contrib.auth.urls')),
    path('profile/', accounts_views.profile, name='user-profile'),
    path('profile/update/', accounts_views.ProfileUpdate.as_view(), name='user-profile-update'),
    path('profile/image_change/', accounts_views.ChangeImageProfileView.as_view(), name='user-image-change'),
    path('detail/<int:pk>/', accounts_views.account, name='user-account'),
]

blog/urls.py
from django.urls import path
from blog import views as blog_views
from django.conf.urls import include, url

app_name = 'blog'

urlpatterns = [
    path('', blog_views.BlogView.as_view(), name='blog-index'),
    path('post/<slug:slug>/', blog_views.view_post, name='blog-view-post'),
    path('new/', blog_views.PostCreateView.as_view(), name='blog-post-new'),
    path('edit/<slug:slug>/', blog_views.PostUpdateView.as_view(), name='blog-post-edit'),
    path('delete/<slug:slug>/', blog_views.PostDeleteView.as_view(), name='blog-post-delete'),
    path('category/<slug:slug>/', blog_views.view_category, name='blog-view-category'),
    path('group/<slug:slug>/', blog_views.view_group, name='blog-view-group'),
    # rich editor urls
    url(r'^tinymce/', include('tinymce.urls')),
]

cash/urls.py
from django.urls import path
from cash import views as cash_views

app_name = 'cash'

urlpatterns = [
    path('', cash_views.EntryListView.as_view(), name='cash-index'),
    path('entry/<slug:slug>/', cash_views.entry_detail_view, name='cash-view-entry'),
    path('entry/new/payment/', cash_views.EntryCreatePayment.as_view(), name='cash-entry-new-payment'),
    path('entry/new/debt/', cash_views.EntryCreateDebt.as_view(), name='cash-entry-new-debt'),
    path('revert/<slug:slug>/', cash_views.RevertEntryView.as_view(), name='cash-entry-revert'),
    # User entries
    path('user_entry/<int:user_target_id>/', cash_views.UserEntryListView.as_view(), name='cash-user-account'),
    path('user_entry/<slug:slug>/', cash_views.user_entry_detail_view, name='cash-view-user-entry'),
    path(
        'user_entry/new/payment/<int:user_target_id>/',
        cash_views.UserEntryCreatePayment.as_view(),
        name='cash-user-entry-new-payment',
    ),
    path(
        'user_entry/new/debt/<int:user_target_id>/',
        cash_views.UserEntryCreateDebt.as_view(),
        name='cash-user-entry-new-debt'
    ),
    path('user_entry/revert/<slug:slug>/', cash_views.RevertUserEntryView.as_view(), name='cash-user-entry-revert'),
]

core/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('members/', include('members.urls')),
    path('cash/', include('cash.urls')),
    path('', include('blog.urls')),
    url(r'^tz_detect/', include('tz_detect.urls')),
]

members/urls.py
from django.urls import path
from members import views as members_views

app_name = 'members'

urlpatterns = [
    path('', members_views.MembersView.as_view(), name='members-index'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% block title %}{{ section.title }}{% endblock %}</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <!-- Page level plugin CSS-->
  <link href="{% static 'vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">
  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">


  
  
<script src="https://cdn.tiny.cloud/1/lgebz6ny33njlyo1g6ju6p5pgtmunsg3hub9xmzuzn1wqtiz/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<script>
    tinymce.init({
      selector: '#id_rich_body'
    });
  </script>
<link type="text/css" rel="stylesheet" href="https://colorlib.com/preview/theme/callie/css/style.css" />
  <link href="{% static 'css/custom.css' %}" rel="stylesheet">

<style>
  img {
    display: inline-block;
    height: auto;
    max-width: 100%;
}
</style>

</head>

{% load tz_detect %}
{% tz_detect %}

<body id="page-top">

{% include "navbar.html" %}

  <div id="wrapper">

    <!-- Sidebar -->
    {% include "sidebar.html" %}

    <div id="content-wrapper">

      <div class="container-fluid">


        {% block breadcrumbs %}
            {% include 'breadcrumbs.html'%}
        {% endblock breadcrumbs %}

        <!-- Breadcrumbs-->
        <!-- <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="#">{% block section %}{{ section.section }}{% endblock %}</a>
          </li>
          <li class="breadcrumb-item active">Overview</li>
        </ol> -->

        
        
		{% block content %}
    	{% endblock %}
       
      <!-- /.container-fluid -->

      <!-- Sticky Footer -->
		{% include "footer.html" %}

    </div>
    <!-- /.content-wrapper -->

  </div>
  <!-- /#wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Estás seguro de salir?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Selecciona "Cerrar sesión" si deseas cerrar tu sesión</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
          <a class="btn btn-danger" href="{% url 'accounts:logout' %}">Cerrar sesión</a>
        </div>
      </div>
    </div>
  </div>


  <!-- Bootstrap core JavaScript-->
 
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>


  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin.min.js' %}"></script>





</body>

</html>

templates/breadcrumbs.html
<div class="breadcrumb">
    {% for crumb in breadcrumbs %}
	    {% if not forloop.last %}
	    <li class="breadcrumb-item">
	        <a class="breadcrumb-item"> {{ crumb.0 }} </a>
	    </li>
	    {% else %}
	    <li class="breadcrumb-item active">
	        <a class="breadcrumb-item active">{{ crumb.0 }}</a>
	    </li>
		    {% if kwargs.slug %}
		    <li class="breadcrumb-item active">
		        <a class="breadcrumb-item active">{{ kwargs.slug }}</a>
		    </li>
		    {% endif %}
		{% endif %}
    {% endfor %}
</div>

templates/footer.html
      <footer class="sticky-footer">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright © Barrio Cloud {% now 'Y' %}</span>
          </div>
        </div>
      </footer>

templates/navbar.html
  <nav class="navbar navbar-expand navbar-dark bg-dark static-top">

    <a class="navbar-brand mr-1" href="index.html">Barrio Cloud</a>

    <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
      <i class="fas fa-bars"></i>
    </button>

    <!-- Navbar Search -->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
      <div class="input-group">
       <!--  <input type="text" class="form-control" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2"> -->
        <div class="input-group-append">
         <!--  <button class="btn btn-primary" type="button">
            <i class="fas fa-search"></i>
          </button> -->
        </div>
      </div>
    </form>

    <!-- Navbar -->
    <ul class="navbar-nav ml-auto ml-md-0">
      
      <!-- Alerts -->
<!--       <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-bell fa-fw"></i>
          <span class="badge badge-danger">9+</span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li> -->
      

      <!-- messages -->
<!--       <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-envelope fa-fw"></i>
          <span class="badge badge-danger">7</span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="messagesDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li> -->

      <!-- Profile -->
      <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-user-circle fa-fw"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
          <!-- AUTH -->
          {% if user.is_authenticated %}
            <h6 class="dropdown-header text-center">{{ user }}</h6>
            <a class="dropdown-item" href="{% url 'accounts:user-profile' %}">Perfil</a>
            <a class="dropdown-item" href="{% url 'accounts:password_change' %}">Cambiar contraseña</a>
            <a class="dropdown-item" href="{% url 'accounts:user-image-change' %}">Cambiar imagen de perfil</a>
              <!-- STAFF -->
              {% if request.user.is_staff %}
                <a class="dropdown-item" href="{% url 'admin:index' %}">Ir a Admin</a>
                <div class="dropdown-divider"></div>
                <h6 class="dropdown-header text-center">Blog</h6>
                <a class="dropdown-item" href="{% url 'blog:blog-post-new' %}">Nuevo artículo</a>
                <div class="dropdown-divider"></div>
                <h6 class="dropdown-header text-center">Caja</h6>
                <a class="dropdown-item" href="{% url 'cash:cash-entry-new-debt' %}">Nuevo gasto</a>
                <a class="dropdown-item" href="{% url 'cash:cash-entry-new-payment' %}">Nuevo pago</a>
              {% endif %}
              <!-- END STAFF -->
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Cerrar sesión</a>
          {% else %}
          <!-- END AUTH -->
            <a class="dropdown-item" href="{% url 'accounts:login' %}">Iniciar Sesión</a>
          {% endif %}
        </div>
      </li>
    </ul>

  </nav>

templates/sidebar.html
    <ul class="sidebar navbar-nav">
      <li class="nav-item {% if request.resolver_match.url_name == 'blog-index' %}active{% endif %}">
        <a class="nav-link" href="{% url 'blog:blog-index' %}">
          <i class="fas fa-fw fa-newspaper"></i>
          <span>Novedades</span></a>
      </li>
      <li class="nav-item {% if request.resolver_match.url_name == 'cash-user-account' %}active{% endif %}">
        <a class="nav-link" href="{% url 'cash:cash-user-account' request.user.pk %}">
          <i class="fas fa-fw fa-user"></i>
          <span>Mi cuenta</span>
        </a>
      </li>
      <li class="nav-item {% if request.resolver_match.url_name == 'members-index' %}active{% endif %}">
        <a class="nav-link" href="{% url 'members:members-index' %}">
          <i class="fas fa-fw fa-users"></i>
          <span>Socios</span></a>
      </li>
      <li class="nav-item {% if request.resolver_match.url_name == 'cash-index' %}active{% endif %}">
        <a class="nav-link" href="{% url 'cash:cash-index' %}">
          <i class="fas fa-fw fa-cash-register"></i>
          <span>Caja</span></a>
      </li>
    </ul>

templates/summary-cards.html
        <div class="row">
          <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-primary o-hidden h-100">
              <div class="card-body">
                <div class="card-body-icon">
                  <i class="fas fa-fw fa-comments"></i>
                </div>
                <div class="mr-5">26 New Messages!</div>
              </div>
              <a class="card-footer text-white clearfix small z-1" href="#">
                <span class="float-left">View Details</span>
                <span class="float-right">
                  <i class="fas fa-angle-right"></i>
                </span>
              </a>
            </div>
          </div>
          <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-warning o-hidden h-100">
              <div class="card-body">
                <div class="card-body-icon">
                  <i class="fas fa-fw fa-list"></i>
                </div>
                <div class="mr-5">11 New Tasks!</div>
              </div>
              <a class="card-footer text-white clearfix small z-1" href="#">
                <span class="float-left">View Details</span>
                <span class="float-right">
                  <i class="fas fa-angle-right"></i>
                </span>
              </a>
            </div>
          </div>
          <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-success o-hidden h-100">
              <div class="card-body">
                <div class="card-body-icon">
                  <i class="fas fa-fw fa-shopping-cart"></i>
                </div>
                <div class="mr-5">123 New Orders!</div>
              </div>
              <a class="card-footer text-white clearfix small z-1" href="#">
                <span class="float-left">View Details</span>
                <span class="float-right">
                  <i class="fas fa-angle-right"></i>
                </span>
              </a>
            </div>
          </div>
          <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-danger o-hidden h-100">
              <div class="card-body">
                <div class="card-body-icon">
                  <i class="fas fa-fw fa-life-ring"></i>
                </div>
                <div class="mr-5">13 New Tickets!</div>
              </div>
              <a class="card-footer text-white clearfix small z-1" href="#">
                <span class="float-left">View Details</span>
                <span class="float-right">
                  <i class="fas fa-angle-right"></i>
                </span>
              </a>
            </div>
          </div>
        </div>