blog/urls.py
from django.urls import path
from blog import views as blog_views
from django.conf.urls import include, url

app_name = 'blog'

urlpatterns = [
    path('', blog_views.BlogView.as_view(), name='blog-index'),
    path('post/<slug:slug>/', blog_views.view_post, name='blog-view-post'),
    path('new/', blog_views.PostCreateView.as_view(), name='blog-post-new'),
    path('edit/<slug:slug>/', blog_views.PostUpdateView.as_view(), name='blog-post-edit'),
    path('delete/<slug:slug>/', blog_views.PostDeleteView.as_view(), name='blog-post-delete'),
    path('category/<slug:slug>/', blog_views.view_category, name='blog-view-category'),
    path('group/<slug:slug>/', blog_views.view_group, name='blog-view-group'),
    # rich editor urls
    url(r'^tinymce/', include('tinymce.urls')),
]

cash/urls.py
from django.urls import path
from cash import views as cash_views

app_name = 'cash'

urlpatterns = [
    path('', cash_views.EntryListView.as_view(), name='cash-index'),
    path('entry/<slug:slug>/', cash_views.entry_detail_view, name='cash-view-entry'),
    path('entry/new/payment/', cash_views.EntryCreatePayment.as_view(), name='cash-entry-new-payment'),
    path('entry/new/debt/', cash_views.EntryCreateDebt.as_view(), name='cash-entry-new-debt'),
    path('revert/<slug:slug>/', cash_views.RevertEntryView.as_view(), name='cash-entry-revert'),
    # User entries
    path('user_entry/<int:user_target_id>/', cash_views.UserEntryListView.as_view(), name='cash-user-account'),
    path('user_entry/<slug:slug>/', cash_views.user_entry_detail_view, name='cash-view-user-entry'),
    path(
        'user_entry/new/payment/<int:user_target_id>/',
        cash_views.UserEntryCreatePayment.as_view(),
        name='cash-user-entry-new-payment',
    ),
    path(
        'user_entry/new/debt/<int:user_target_id>/',
        cash_views.UserEntryCreateDebt.as_view(),
        name='cash-user-entry-new-debt'
    ),
    path('user_entry/revert/<slug:slug>/', cash_views.RevertUserEntryView.as_view(), name='cash-user-entry-revert'),
]

core/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('members/', include('members.urls')),
    path('cash/', include('cash.urls')),
    path('', include('blog.urls')),
    url(r'^tz_detect/', include('tz_detect.urls')),
]

cash/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from django.contrib.auth.models import User
from djmoney.models.fields import MoneyField
from tinymce.models import HTMLField


class TimestampleModel(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    deleted = models.BooleanField(default=False)

    class Meta:
        abstract = True


class EntryType(TimestampleModel):
    title = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('cash:cash-view-entry-type', args=[self.slug])

    def save(self, *args, **kwargs):
        self.slug = slugify('{title}-{id}'.format(title=self.title, id=self.pk))
        super(EntryType, self).save(*args, **kwargs)

    class Meta:
        ordering = ['title']


class Entry(TimestampleModel):
    detail = models.CharField(max_length=250)
    amount = MoneyField(max_digits=19, decimal_places=2, default_currency='ARS')
    balance = MoneyField(max_digits=19, decimal_places=2, default_currency='ARS')
    notes = HTMLField(blank=True, null=True)
    attached_file_url = models.CharField(max_length=250, blank=True, null=True)
    slug = models.SlugField(max_length=250)
    entry_type = models.ForeignKey(EntryType, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.detail

    def get_absolute_url(self):
        return reverse('cash:cash-view-entry', args=[self.slug])

    def save(self, *args, **kwargs):
        self.slug = slugify('{title}-{id}'.format(title=self.detail, id=self.pk))
        super(Entry, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-created_date']


class UserEntry(TimestampleModel):
    detail = models.CharField(max_length=250)
    amount = MoneyField(max_digits=19, decimal_places=2, default_currency='ARS')
    balance = MoneyField(max_digits=19, decimal_places=2, default_currency='ARS')
    notes = HTMLField(blank=True, null=True)
    attached_file_url = models.CharField(max_length=250, blank=True, null=True)
    slug = models.SlugField(max_length=250)
    entry_type = models.ForeignKey(EntryType, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='session_user')
    target_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='target_user')

    def __str__(self):
        return self.detail

    def get_absolute_url(self):
        return reverse('cash:cash-view-user-entry', args=[self.slug])

    def save(self, *args, **kwargs):
        self.slug = slugify('{title}-{id}'.format(title=self.detail, id=self.pk))
        super(UserEntry, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-created_date']

cash/forms.py
from django import forms


class RevertEntryForm(forms.Form):
    pk = forms.IntegerField(label='Entry Pk')

cash/views.py
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User

from cash.models import Entry, UserEntry, EntryType
from cash.forms import RevertEntryForm

from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.views import View

from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.http import Http404
from django.shortcuts import render

from django.utils.decorators import method_decorator

from djmoney.money import Money

from common.upload import upload_file


def get_new_balance(new_amount, currency):
    try:
        latest = Entry.objects.latest('created_date')
    except Entry.DoesNotExist:
        latest = None
    balance = Money(0, currency)
    if latest:
        balance += latest.balance + new_amount
    else:
        balance += new_amount
    return balance


def get_balance_status(balance):
    zero = Money(0, balance.currency)
    if balance < zero:
        status = {
            'text': 'DEUDA',
            'style': 'danger',
        }
    elif balance == zero:
        status = {
            'text': 'SIN FONDOS',
            'style': 'warning',
        }
    else:
        status = {
            'text': 'SUPERÁVIT',
            'style': 'success',
        }
    return status


@method_decorator(login_required, name='dispatch')
class EntryListView(ListView):
    template_name = 'cash/index.html'
    model = Entry
    paginate_by = 50  # if pagination is desired
    context_object_name = 'entries'
    ordering = ['-created_date']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        balance = get_new_balance(0, 'ARS')
        balance_status = get_balance_status(balance)
        context['balance_status'] = balance_status
        context['balance'] = balance
        return context


@login_required
def entry_detail_view(request, slug):
    try:
        entry = Entry.objects.get(slug=slug)
    except Entry.DoesNotExist:
        raise Http404("Entry does not exist")
    return render(request, 'cash/view_entry.html', {'entry': entry})


def get_entry_amount(amount, currency, entry_type):
    zero = Money(0, currency)
    if entry_type == 'GASTO':
        return amount if amount < zero else (amount * -1)
    elif entry_type == 'PAGO':
        return amount if amount > zero else (amount * -1)
    raise Exception('Entry type not supported')


@method_decorator(staff_member_required, name='dispatch')
@method_decorator(login_required, name='dispatch')
class EntryCreateDebt(CreateView):
    model = Entry
    fields = ['detail', 'amount', 'notes']

    def form_valid(self, form):
        entry = form.save(commit=False)
        links = upload_file(self.request, 'attached_file')
        entry.attached_file_url = links['dropbox']
        entry.user = self.request.user
        entry.amount = get_entry_amount(entry.amount, entry.amount.currency, 'GASTO')
        entry.balance = get_new_balance(
            entry.amount,
            entry.amount.currency,
        )
        entry.entry_type = EntryType.objects.get(title='Gasto')
        entry.save()
        response = super(EntryCreateDebt, self).form_valid(form)
        return response


@method_decorator(staff_member_required, name='dispatch')
@method_decorator(login_required, name='dispatch')
class EntryCreatePayment(CreateView):
    model = Entry
    fields = ['detail', 'amount', 'notes']

    def form_valid(self, form):
        entry = form.save(commit=False)
        links = upload_file(self.request, 'attached_file')
        entry.attached_file_url = links['dropbox']
        entry.user = self.request.user
        entry.amount = get_entry_amount(entry.amount, entry.amount.currency, 'PAGO')
        entry.balance = get_new_balance(
            entry.amount,
            entry.amount.currency,
        )
        entry.entry_type = EntryType.objects.get(title='Pago')
        entry.save()
        response = super(EntryCreatePayment, self).form_valid(form)
        return response


@method_decorator(staff_member_required, name='dispatch')
@method_decorator(login_required, name='dispatch')
class RevertEntryView(View):
    form_class = RevertEntryForm
    template_name = 'cash/revert_entry.html',

    def get(self, request, slug):
        form = self.form_class()
        try:
            entry = Entry.objects.get(slug=slug)
        except Entry.DoesNotExist:
            raise Http404("Entry does not exist")
        return render(request, self.template_name, {'entry': entry, 'form': form})

    def post(self, request, slug):
        form = self.form_class(request.POST)
        try:
            entry_to_revert = Entry.objects.get(slug=slug)
        except Entry.DoesNotExist:
            raise Http404("Entry does not exist")
        if form.is_valid():
            detail = 'reverted-({})'.format(entry_to_revert.detail)
            reverted_amount = entry_to_revert.amount * (-1)
            balance = get_new_balance(reverted_amount, entry_to_revert.amount.currency)
            reverted_entry = Entry.objects.create(
                detail=detail,
                amount=reverted_amount,
                balance=balance,
                user=self.request.user,
                entry_type=entry_to_revert.entry_type,
            )
            reverted_entry.save()
            return HttpResponseRedirect(reverse_lazy('cash:cash-index'))


def get_new_user_balance(new_amount, currency, target_user_id):
    try:
        latest = UserEntry.objects.filter(target_user=target_user_id).latest('created_date')
    except UserEntry.DoesNotExist:
        latest = None
    balance = Money(0, currency)
    if latest:
        balance += latest.balance + new_amount
    else:
        balance += new_amount
    return balance


def get_user_entry_amount(amount, currency, entry_type):
    zero = Money(0, currency)
    if entry_type == 'GASTO':
        return amount if amount > zero else (amount * -1)
    elif entry_type == 'PAGO':
        return amount if amount < zero else (amount * -1)
    raise Exception('Entry type not supported')


def get_user_balance_status(balance):
    zero = Money(0, balance.currency)
    if balance > zero:
        status = {
            'text': 'A PAGAR',
            'style': 'warning',
        }
    elif balance == zero:
        status = {
            'text': 'AL DÍA',
            'style': 'success',
        }
    else:
        status = {
            'text': 'A FAVOR',
            'style': 'info',
        }
    return status


@method_decorator(login_required, name='dispatch')
class UserEntryListView(ListView):
    template_name = 'cash/user_index.html'
    model = UserEntry
    paginate_by = 50  # if pagination is desired
    context_object_name = 'entries'
    ordering = ['-created_date']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_balance = get_new_user_balance(0, 'ARS', self.kwargs.get('user_target_id'))
        balance_status = get_user_balance_status(user_balance)
        context['balance'] = user_balance
        context['balance_status'] = balance_status
        context['member'] = User.objects.get(pk=self.kwargs.get('user_target_id'))
        return context

    def get_queryset(self):
        queryset = super(UserEntryListView, self).get_queryset()
        user_target_id = self.kwargs.get('user_target_id')
        user_entries = queryset.filter(target_user=user_target_id)
        return user_entries


@login_required
def user_entry_detail_view(request, slug):
    try:
        p = UserEntry.objects.get(slug=slug)
    except UserEntry.DoesNotExist:
        raise Http404("Entry does not exist")
    return render(request, 'cash/view_user_entry.html', {'entry': p})


@method_decorator(staff_member_required, name='dispatch')
@method_decorator(login_required, name='dispatch')
class UserEntryCreateDebt(CreateView):
    model = UserEntry
    fields = ['detail', 'amount', 'notes']

    def form_valid(self, form):
        user_entry = form.save(commit=False)
        links = upload_file(self.request, 'attached_file')
        user_entry.attached_file_url = links['dropbox']
        user_entry.target_user = User.objects.get(pk=self.kwargs.get('user_target_id'))
        user_entry.user = self.request.user
        user_entry.amount = get_user_entry_amount(user_entry.amount, user_entry.amount.currency, 'GASTO')
        user_entry.balance = get_new_user_balance(
            user_entry.amount,
            user_entry.amount.currency,
            self.kwargs.get('user_target_id'),
        )
        user_entry.entry_type = EntryType.objects.get(title='Gasto')
        user_entry.save()
        response = super(UserEntryCreateDebt, self).form_valid(form)
        return response


@method_decorator(staff_member_required, name='dispatch')
@method_decorator(login_required, name='dispatch')
class UserEntryCreatePayment(CreateView):
    model = UserEntry
    fields = ['detail', 'amount', 'notes']

    def form_valid(self, form):
        user_entry = form.save(commit=False)
        links = upload_file(self.request, 'attached_file')
        user_entry.attached_file_url = links['dropbox']
        user_entry.target_user = User.objects.get(pk=self.kwargs.get('user_target_id'))
        user_entry.user = self.request.user
        user_entry.amount = get_user_entry_amount(user_entry.amount, user_entry.amount.currency, 'PAGO')
        user_entry.balance = get_new_user_balance(
            user_entry.amount,
            user_entry.amount.currency,
            self.kwargs.get('user_target_id'),
        )
        user_entry.entry_type = EntryType.objects.get(title='Pago')
        user_entry.save()
        response = super(UserEntryCreatePayment, self).form_valid(form)
        return response


@method_decorator(staff_member_required, name='dispatch')

templates/cash/entry_confirm_delete.html
{% extends 'base.html' %}
{% load i18n %} 
{% block title %}Blog{% endblock %}
{% block section %}Post{% endblock %}

{% block content %}

{% trans "Estás seguro de que quieres eliminar a " as question %}
{% trans "Confirmar" as msg_btn %}


<form method="post">{% csrf_token %}
    <p>{{ question }} "{{ object }}"?</p>
    <input class="btn btn-danger" type="submit" value="{{ msg_btn }}">
</form>
	
{% endblock %}

templates/cash/index.html
{% extends 'base.html' %}
{% load i18n %} 
{% load djmoney %}

{% block title %}Cash{% endblock %}
{% block section %}Cash{% endblock %}

{% block content %}

{% trans "Caja" as cash_title %}
{% trans "No hay entradas." as no_entries_message %}

<div class="jumbotron p-4 p-md-5 rounded">
    <h1 class="font-italic text-center">{{ cash_title }}</h1>
    <h1 class="font-italic text-center">Fondos: {{ balance }} <span class="badge badge-{{ balance_status.style }}">{{ balance_status.text }}</span></h1>
</div>


{% if request.user.is_staff %}      
<div class="p-4">
  <a class="btn btn-success" href="{% url 'cash:cash-entry-new-payment' %}" role="button">
    Ingresar Pago
  </a>
  <a class="btn btn-secondary" href="{% url 'cash:cash-entry-new-debt' %}" role="button">
    Ingresar Gasto
  </a>
</div>
{% endif %}

<main role="main">
  <div class="row">

  
    <div class="col-md-12 blog-main">
      {% if entries %}

          <table class="table table-striped">
          <thead>
            <tr>
              <th style="width: 5%">#</th>
              <th style="width: 15%">Date</th>
              <th style="width: 35%">Detail</th>
              <th style="width: 15%">Amount</th>
              <th style="width: 15%">Balance</th>
              <th style="width: 5%">Actions</th>
            </tr>
          </thead>
          <tbody>
        {% for entry in entries %}    
            <tr>
              <td>{{ entry.pk }}</td>
              <td>{{ entry.created_date }}</td>
              <td><a href="{{ entry.get_absolute_url }}"> {{ entry.detail }}</a></td>
              <td>{{ entry.amount }}</td>
              <td>{{ entry.balance }}</td>
              
              <td>
                {% if request.user.is_staff %}
                <a class="btn btn-sm btn-danger" style="color: white;" href="{% url 'cash:cash-entry-revert' entry.slug %}">Revertir</a>
                {% endif %}
                <a class="btn btn-sm btn-info" style="color: white;" href="{{ entry.get_absolute_url }}">Ver</a>
              </td>
              
            </tr>
        {% endfor %}
        </tbody>
        </table>
      <!-- END POST -->
      {% else %}
          <p>{{ no_entries_message }}</p>
      {% endif %}
    
        <!-- Pagination -->
        <div class="d-flex justify-content-center mb-3">
            {% if is_paginated %}
            <nav>
              <ul class="pagination">
                {% if page_obj.has_previous %}
                  <li class="page-item"><a class="page-link"  href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                {% else %}
                  <li class="page-item disabled"><span class="page-link" >&laquo;</span></li>
                {% endif %}
                {% for i in paginator.page_range %}
                  {% if page_obj.number == i %}
                    <li class="page-item active"><span class="page-link" >{{ i }} <span class="sr-only">(current)</span></span></li>
                  {% else %}
                    <li class="page-item"><a class="page-link"  href="?page={{ i }}">{{ i }}</a></li>
                  {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                  <li class="page-item"><a class="page-link"  href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                {% else %}
                  <li class="page-item disabled"><span class="page-link" >&raquo;</span></li>
                {% endif %}
              </ul>
            </nav>
          {% endif %}
        </div>
         <!-- Pagination -->

    </div><!-- /.blog-main -->

  </div><!-- /.row -->

</main>


{% endblock %}

templates/cash/revert_entry.html
{% extends 'base.html' %}

{% block title %}Blog{% endblock %}
{% block section %}Post{% endblock %}

{% block content %}

<div class="col-md-4">
	<div class="post post-sm">
	<div class="post-body">
		<h1 class=""><a href="{{ entry.get_absolute_url }}">
		Está seguro que quiere revertir la operación: #{{ entry.pk }} ?
		<br>
		{{ entry.detail }}
		</a></h1>
		<ul class="post-meta">
			<li>{{ entry.user }}</li>
			<li>{{ entry.created_date }}</li>
		</ul>
	</div>
	</div>
</div>

   <img class="card-img-top"  style="max-width:50%;height:auto;" src="{{ post.image_url }}" alt={{ post.title }}>
   <p class="display-2">{{ entry.amount }}</p>
   <p class="display-2">{{ entry.balance }}</p>

	  <form method="post">
	    {% csrf_token %}
	    <input type="hidden" id="id_pk" name="pk" value="{{ entry.pk }}">
	    <button class="btn btn-outline-primary text-uppercase" type="submit">Revertir</button>
	</form>
	

{% endblock %}

templates/cash/revert_user_entry.html
{% extends 'base.html' %}

{% block title %}Cash{% endblock %}
{% block section %}Revert{% endblock %}

{% block content %}

<div class="col-md-4">
	<div class="post post-sm">
	<div class="post-body">
		<h1 class=""><a href="{{ entry.get_absolute_url }}">
		Está seguro que quiere revertir la operación: #{{ entry.pk }} ?
		<br>
		{{ entry.detail }}
		</a></h1>
		<ul class="post-meta">
			<li>{{ entry.user }}</li>
			<li>{{ entry.created_date }}</li>
		</ul>
	</div>
	</div>
</div>

   <img class="card-img-top"  style="max-width:50%;height:auto;" src="{{ post.image_url }}" alt={{ post.title }}>
   <p class="display-2">{{ entry.amount }}</p>
   <p class="display-2">{{ entry.balance }}</p>

	  <form method="post">
	    {% csrf_token %}
	    <input type="hidden" id="id_pk" name="pk" value="{{ entry.pk }}">
	    <button class="btn btn-outline-primary text-uppercase" type="submit">Revertir</button>
	</form>
	

{% endblock %}

templates/cash/user_index.html
{% extends 'base.html' %}
{% load i18n %} 
{% load djmoney %}

{% block title %}Cash{% endblock %}
{% block section %}Cash{% endblock %}

{% block content %}

{% trans "Cuenta" as cash_title %}
{% trans "No hay entradas." as no_entries_message %}

<div class="jumbotron p-4 p-md-5 rounded">
    <h1 class="font-italic text-center">{{ cash_title }}</h1>
    <h1 class="font-italic text-center">{{ member }}</h1>
    <h1 class="font-italic text-center">Saldo total: {{ balance }} <span class="badge badge-{{ balance_status.style }}">{{ balance_status.text }}</span></h1>
    

</div>

{% if request.user.is_staff %}      
<div class="p-4">
  <a class="btn btn-success" href="{% url 'cash:cash-user-entry-new-payment' member.id %}" role="button">
    Ingresar Pago
  </a>
  <a class="btn btn-secondary" href="{% url 'cash:cash-user-entry-new-debt' member.id %}" role="button">
    Ingresar Gasto
  </a>
</div>
{% endif %}

<main role="main">
  <div class="row">

  
    <div class="col-md-12 blog-main">
      {% if entries %}

          <table class="table table-striped">
          <thead>
            <tr>
              <th style="width: 5%">#</th>
              <th style="width: 15%">Date</th>
              <th style="width: 35%">Detail</th>
              <th style="width: 15%">Amount</th>
              <th style="width: 15%">Balance</th>
              <th style="width: 5%">Actions</th>
            </tr>
          </thead>
          <tbody>
        {% for entry in entries %}    
            <tr>
              <td>{{ entry.pk }}</td>
              <td>{{ entry.created_date }}</td>
              <td><a href="{{ entry.get_absolute_url }}"> {{ entry.detail }}</a></td>
              <td>{{ entry.amount }}</td>
              <td>{{ entry.balance }}</td>
              <td>
                {% if request.user.is_staff %}
                <a class="btn btn-sm btn-danger" style="color: white;" href="{% url 'cash:cash-user-entry-revert' entry.slug %}">Revertir</a>
                {% endif %}
                <a class="btn btn-sm btn-info" style="color: white;" href="{{ entry.get_absolute_url }}">Ver</a>
              </td>
            </tr>
        {% endfor %}
        </tbody>
        </table>
      <!-- END POST -->
      {% else %}
          <p>{{ no_entries_message }}</p>
      {% endif %}
    
        <!-- Pagination -->
        <div class="d-flex justify-content-center mb-3">
            {% if is_paginated %}
            <nav>
              <ul class="pagination">
                {% if page_obj.has_previous %}
                  <li class="page-item"><a class="page-link"  href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                {% else %}
                  <li class="page-item disabled"><span class="page-link" >&laquo;</span></li>
                {% endif %}
                {% for i in paginator.page_range %}
                  {% if page_obj.number == i %}
                    <li class="page-item active"><span class="page-link" >{{ i }} <span class="sr-only">(current)</span></span></li>
                  {% else %}
                    <li class="page-item"><a class="page-link"  href="?page={{ i }}">{{ i }}</a></li>
                  {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                  <li class="page-item"><a class="page-link"  href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                {% else %}
                  <li class="page-item disabled"><span class="page-link" >&raquo;</span></li>
                {% endif %}
              </ul>
            </nav>
          {% endif %}
        </div>
         <!-- Pagination -->

    </div><!-- /.blog-main -->

  </div><!-- /.row -->

</main>


{% endblock %}

templates/cash/view_entry.html
{% extends 'base.html' %}

{% block title %}Blog{% endblock %}
{% block section %}Post{% endblock %}

{% load cash_extras %}

{% block content %}

<div class="col-md-4">
	<div class="post post-sm">
	<div class="post-body">
		<h1 class=""><a href="{{ entry.get_absolute_url }}">{{ entry.detail }}</a></h1>
		<ul class="post-meta">
			<li>{{ entry.user }}</li>
			<li>{{ entry.created_date }}</li>
			<li>{{ entry.entry_type }}</li>
			{% if request.user.is_staff %}
			<li><a class="btn btn-sm btn-danger" style="color: white;" href="{% url 'cash:cash-entry-revert' entry.slug %}">Revert</a></li>
			{% endif %}
		</ul>
	</div>
	</div>
	{% if entry.attached_file_url %}
		<p class="btn btn-warning text-white"><a href="{{ entry.attached_file_url }} ">Descargar Comprobante</a></p>
		<p class="btn btn-info text-white"><a target="blank" href="{{ entry.attached_file_url|cut:'?dl=1' }} ">Ver Comprobante</a></p>
	{% endif %}
</div>

   <img class="card-img-top"  style="max-width:50%;height:auto;" src="{{ post.image_url }}" alt={{ post.title }}>
   <p class="display-2">{{ entry.amount }}</p>
   <p class="display-2">{{ entry.balance }}</p>  
	

{% endblock %}

templates/cash/view_user_entry.html
{% extends 'base.html' %}

{% block title %}Blog{% endblock %}
{% block section %}Post{% endblock %}

{% load cash_extras %}

{% block content %}

<div class="col-md-4">
	<div class="post post-sm">
	<div class="post-body">
		<h1 class=""><a href="{{ entry.get_absolute_url }}">{{ entry.detail }}</a></h1>
		<a class="btn btn-sm btn-secondary" href="{% url 'cash:cash-user-account' entry.target_user.id %}" role="button">{{ entry.target_user }}</a>
		<ul class="post-meta">
			<li>{{ entry.user }}</li>
			<li>{{ entry.created_date }}</li>
			{% if request.user.is_staff %}
			<li><a class="btn btn-sm btn-danger" style="color: white;" href="{% url 'cash:cash-entry-revert' entry.slug %}">Revert</a></li>
			{% endif %}
		</ul>
	</div>
	</div>
	{% if entry.attached_file_url %}
		<p class="btn btn-warning text-white"><a href="{{ entry.attached_file_url }} ">Descargar Comprobante</a></p>
		<p class="btn btn-info text-white"><a target="blank" href="{{ entry.attached_file_url|cut:'?dl=1' }} ">Ver Comprobante</a></p>
	{% endif %}
</div>

   <img class="card-img-top"  style="max-width:50%;height:auto;" src="{{ post.image_url }}" alt={{ post.title }}>
   <p class="display-2">{{ entry.amount }}</p>
   <p class="display-2">{{ entry.balance }}</p>

	

{% endblock %}